owner: codescientist703 # GitHub username
repo: Test # GitHub repository name
sites: # List of endpoints to track
  - name: Coding Abs
    url: https://codingabs.com
assignees: # Users to assign downtime issues (optional)
  - codescientist703
status-website:
  baseUrl: /Test # where "repo" is your repository name
  name: Coding Abs status