owner: codescientist703 # GitHub username
repo: upptime # GitHub repository name
sites: # List of endpoints to track
  - name: Coding Abs
    url: https://codingabs.com
assignees: # Users to assign downtime issues (optional)
  - codescientist703
